version: '3.9'
services:
  db:
    image: mongo
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: victor3000
      MONGO_INITDB_ROOT_PASSWORD: test3000
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

  db_web_interface:
    image: mongo-express
    restart: always
    container_name: six-cities_mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://victor3000:test3000@db:27017/

volumes:
  six-cities_data: