# Пользователи
## Регистрирует нового пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Мишаня",
  "email": "yamisha@yandex.ru",
  "userpic": "avatar.png",
  "password": "pass123",
  "isPro": false
}


### Авторизует пользователя на основе логина и пароля
# Проверка JWT токена: https://jwt.io/
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "yamisha@yandex.ru",
  "password": "pass123"
}

### Отправка аватарки пользователю
POST http://localhost:4000/users/647ca1b5c529f56cd2734a60/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/tmp/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InlhbWlzaGFAeWFuZGV4LnJ1IiwiaWQiOiI2NDk4MTM2NTUzNzQyODQ2MTE1Y2Q2NzUiLCJpYXQiOjE2ODc2ODgwNzgsImV4cCI6MTY4Nzg2MDg3OH0.nlNFCKJ4v15UIvCBYpwS5Y4NAxjsUttynRPAGExe0mc

###